from __future__ import annotations

import json
from pathlib import Path
from typing import Any


LOCK_FILENAME = "skills-lock.json"


def empty_skills_lock() -> dict[str, Any]:
    """Return the lock shape generated by the official `skills` CLI."""
    return {"version": 1, "skills": {}}


def ensure_skills_lock(project: Path) -> dict[str, Any]:
    """Read the project lock, creating an official-compatible empty lock."""
    root = project.expanduser().resolve()
    assert_consumer_project(root)
    path = root / LOCK_FILENAME
    if not path.exists():
        root.mkdir(parents=True, exist_ok=True)
        _write_lock(path, empty_skills_lock())
    return read_skills_lock(root)


def read_skills_lock(project: Path) -> dict[str, Any]:
    path = project.expanduser().resolve() / LOCK_FILENAME
    if not path.is_file():
        return empty_skills_lock()
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(f"lock inválido: {path}: {error.msg}") from error
    if not isinstance(payload, dict):
        raise ValueError(f"lock inválido: {path}")
    if payload.get("version") != 1:
        raise ValueError(f"versão de lock não suportada em {path}")
    skills = payload.get("skills")
    if not isinstance(skills, dict):
        raise ValueError(f"campo skills inválido em {path}")
    return payload


def installed_skill_names(project: Path, *, create: bool = True) -> set[str]:
    payload = ensure_skills_lock(project) if create else read_skills_lock(project)
    return set(payload["skills"])


def skills_lock_fingerprint(project: Path) -> str:
    path = project.expanduser().resolve() / LOCK_FILENAME
    if not path.is_file():
        return "missing"
    try:
        stat = path.stat()
        return f"{stat.st_mtime_ns}:{stat.st_size}"
    except OSError:
        return "unreadable"


def assert_consumer_project(project: Path) -> None:
    agents = project / "AGENTS.md"
    if not agents.is_file():
        return
    content = agents.read_text(encoding="utf-8", errors="ignore").lower()
    if (
        "monorepo oficial do specsfy" in content
        or "workspace specsfy dev" in content
    ):
        raise ValueError("operação recusada no monorepo oficial do Specsfy")


def _write_lock(path: Path, payload: dict[str, Any]) -> None:
    temporary = path.parent / f".{path.name}.specsfy.tmp"
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)
